learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from loginapp.views import index, special, user_logout

urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('loginapp/',include('loginapp.urls')),
    path('logout/', user_logout, name="user_logout"),
    path('special/', special, name="special")
]

learning_users/loginapp/urls.py
from django.urls import path
from loginapp.views import register,user_login

app_name = "loginapp"

urlpatterns = [
    path('', register, name="register"),
    path('login/', user_login, name = "user_login")

]

learning_users/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #addition
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/loginapp/forms.py
from django import forms
from django.contrib.auth.models import User
from loginapp.models import UserProfileInfo



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['first_name', 'last_name','username','email','password']

class UserprofileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        exclude = ['user',]

learning_users/loginapp/views.py
from django.shortcuts import render
from loginapp.forms import UserForm , UserprofileInfo
from django.contrib.auth.models import User

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, "loginapp/index.html")

@login_required
def special(request):
    return render(request, 'loginapp/special.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def register(request):
    registered = False

    if request.method == 'POST':
        form = UserForm(request.POST)
        profile_form = UserprofileInfo(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(form.errors, profile_form.errors)
    else:
        form = UserForm()
        profile_form = UserprofileInfo()

    return render(request,"loginapp/registration.html",{'form':form , 'profile_form':profile_form, 'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print(f"Username : {username} and password: {password}")
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'loginapp/login.html',{})

learning_users/templates/loginapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>{% block block_title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.bundle.js'%}" type="text/javascript">
    </script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'home'%}"> <img src="{% static 'images/clouds.png'%}" alt="" width="50" height="44" class="d-inline-block align-text-top"> Medic</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link {% block home_class %}active{% endblock %}" aria-current="page" href="{%url 'home'%}">Home</a>
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-link {% block register_class %}{% endblock %}" href="{% url 'loginapp:register' %}">Register</a>
            {% if user.is_authenticated %}
                    <a class="nav-link {% block logout_class %}{% endblock %}" href="{% url 'user_logout' %}">Logout</a>
                    <a class="nav-link {% block special_class %}{% endblock %}" href="{% url 'special' %}">special</a>

            {% else %}
                   <a class="nav-link {% block login_class %}{% endblock %}" href="{% url 'loginapp:user_login' %}">Login</a>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>



    <!-- <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{%url 'home'%}">Home</a></li>
          <li><a class="nav-link" href="{% url 'loginapp:register' %}"> Register</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}"> Admin </a></li>
        </ul>

      </div>

    </nav> -->
{% block body_block%}

{% endblock %}

  </body>
</html>

learning_users/templates/loginapp/index.html
<!DOCTYPE html>
{% extends 'loginapp/base.html' %}
{% block block_title %}Home{% endblock %}

{% block body_block%}
<div class="container p-5 mt-4 bg-light rounded-3 ">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Welcome to my website</h1>
    <p class="col-md-8 fs-4">The site is in contruction, please navigate to the bar ebove to go to admin or to register to our mailling list</p>
  </div>
</div>
{% endblock %}

learning_users/templates/loginapp/login.html
{% extends 'loginapp/base.html'%}
{% block login_class %}active{% endblock %}
{% block home_class %}{% endblock %}"

{% block body_block %}

<div class="container p-5 mt-4 bg-light rounded-3 ">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Please Login</h1>
    <form action="{% url 'loginapp:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username</label>
      <input type="text" name="username" value="" placeholder="Type in your username">

      <label for="password">Password</label>
      <input type="password" name="password" value="">

      <input class="btn btn-light" style="background-color : #bde0fe;" type="submit" name="" value="Login">

    </form>
  </div>
</div>

{% endblock %}

learning_users/templates/loginapp/registration.html
<!DOCTYPE html>
{% extends 'loginapp/base.html' %}

{% block block_title %}Registration{% endblock %}

{% block home_class %}{% endblock %}
{% block register_class %}active{% endblock %}

{% block body_block%}
<div class=" container p-5 mt-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    {% if registered %}
      <h1 class="display-5 fw-bold">Thank you for registering </h1>
    {% else %}
      <h1 class="display-5 fw-bold">Register Here!</h1>
      <p class="col-md-8 fs-4">Fill out the form:</p>
      <form class="form-control" enctype="multipart/form-data"  method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        {{ profile_form.as_p }}

        <input class="btn btn-light" style="background-color : #bde0fe;" type="submit" value="Register">
      </form>
      {% endif %}
  </div>
</div>



{% endblock %}

learning_users/templates/loginapp/special.html
{% extends 'loginapp/base.html'%}
{% block special_class %}active{% endblock %}
{% block home_class %}{% endblock %}"

{% block body_block %}

<div class="container p-5 mt-4 bg-light rounded-3 ">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">You are logged in , Nice!</h1>
    <p class="col-md-8 fs-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

{% endblock %}